name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
      - 'feature/**'
      - 'docs/**'
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request:
    branches:
      - develop
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader
          npm ci

      - name: Build Assets
        run: npm run build

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Prepare SQLite and Migrate
        run: |
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate --graceful --ansi

      - name: PHP Style (Pint)
        run: vendor/bin/pint --test

      - name: Frontend Lint (ESLint)
        run: npm run lint

      - name: Tests (Pest)
        run: ./vendor/bin/pest
